# Generated by Django 5.0.7 on 2024-07-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adequacy', models.SmallIntegerField(blank=True, null=True)),
                ('arrival', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[(1, 'Collecting Documents'), (2, 'University Choice'), (3, 'Residence Permit'), (4, 'Preparing to Move')], default=1, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='CollectingDocumetsStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stage')),
            ],
            bases=('core.stage',),
        ),
        migrations.CreateModel(
            name='PreparingToMoveStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stage')),
            ],
            bases=('core.stage',),
        ),
        migrations.CreateModel(
            name='ResidencePermitStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stage')),
            ],
            bases=('core.stage',),
        ),
        migrations.CreateModel(
            name='UniversityChoiceStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stage')),
            ],
            bases=('core.stage',),
        ),
        migrations.AddField(
            model_name='stage',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[(1, 'Technical'), (2, 'IT'), (3, 'Humanitarian'), (4, 'Creative'), (5, 'Economic'), (6, 'Natural science')], max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='universities',
            field=models.ManyToManyField(blank=True, through='core.Specialization', to='core.university'),
        ),
    ]
