# Generated by Django 5.0.7 on 2024-08-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_university_options_student_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
